name: Pull updated data

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull the most recent data
      run: |
        curl -o '_data/predictions.csv' 'https://raw.githubusercontent.com/viralemergence/Fresnel/master/BinaryWebsite.csv'
